[Application]
ServiceName="user_service"
ServerPort=10006

[UserDB]
Host="localhost"
Port=6432
User="postgres"
Password="postgres"
Database="postgres"

[Token]
Key="privatekey"
Expiry=10
RefreshTokenExpiry=5